name: web_and_terminal_pay
description: "payment module from staff"
version: 1.0.0+1
repository: https://github.com/Taverz/web_and_terminal_pay
homepage: https://github.com/Taverz/web_and_terminal_pay
issue_trackerполе: https://github.com/Taverz/web_and_terminal_pay/issue

environment:
  sdk: '>=3.2.0 <4.0.0'
  # flutter: ">=1.17.0"

platforms:
  android:
  ios:
  windows:

dependencies:
  
  dio: ^5.4.3+1
  
  flutter:
    sdk: flutter

  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3

  async: ^2.10.0 
  collection: ^1.16.0 

  shared_preferences: ^2.2.3
  uuid: ^3.0.7

  pos_payment_terminal: ^1.0.5
    # path: ../ttk_dart-main
  atol_online_dart:  ^1.1.2
    # path: ../atol_online/atol_online_dart

  ## В этой папке вынесены все реальные авторизационные данные аккаунтов для тестирования оплаты, 
  ## в реальном приложении не используются, это можно удалить
  # test_data_folder: 
  #   path: ../test_data_folder

  sqlite3_flutter_libs: ^0.5.23
  # drift: ^2.18.0
  filesystem_picker: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  # drift_dev: ^2.18.0
  # dart_code_metrics_presets: any
  # dart_code_metrics: any
  mockito: any
  test: ^1.16.0

flutter:

# dart run dart_code_metrics:metrics analyze lib
dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml

# web_and_terminal_pay % dart run dart_code_metrics:metrics analyze lib

# Building package executable... (3.1s)
# Built dart_code_metrics:metrics.
# This package is entering the deprecation process and will be fully discontinued on July 16th.
# You can read more in this blog post https://dcm.dev/blog/2023/06/06/announcing-dcm-free-version-sunset/.

# We are grateful to you for being a DCM user. If you are a DCM contributor, you can apply for a special license, feel free to reach out to info@dcm.dev.

# If you think DCM is valuable and it helps you, please consider to upgrade to the new Individuals or Teams version.

# To hide this message pass the 'disable-sunset-warning' option.

# ✔ Analysis is completed. Preparing the results: 10.1s

# ✔ no issues found!
# nikitakovalevta